services:
  database:
    image: postgres:alpine
    container_name: terrarium-database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: terrarium-backend
    restart: unless-stopped
    environment:
      - ENV=${ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - API_KEY=${API_KEY}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=${DISCORD_REDIRECT_URI}
    depends_on:
      - database

  frontend:
    build: ./frontend
    container_name: terrarium-frontend
    restart: unless-stopped
    volumes:
      - frontend_assets:/app/dist
    depends_on:
      - backend

  proxy:
    image: nginx:alpine-slim
    container_name: terrarium-proxy
    restart: unless-stopped
    ports:
      - "80:80" # Only port exposed to the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_assets:/var/www/frontend:ro
    depends_on:
      - frontend
      - backend

  tunnel:
    image: ngrok/ngrok:alpine
    container_name: terrarium-tunnel
    restart: unless-stopped
    command: http proxy:80
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - proxy

volumes:
  postgres_data:
  frontend_assets:
