[project]
name = "terrarium-api"
version = "0.1.0"
description = "FastAPI Backend : SystÃ¨me IoT de Monitoring de Plantes"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.126.0",
]
